Thirteenth Workflow 2

diff --git a/.github/workflows/thirteenth_workflow.yml b/.github/workflows/thirteenth_workflow.yml
--- a/.github/workflows/thirteenth_workflow.yml
+++ b/.github/workflows/thirteenth_workflow.yml
@@ -2,6 +2,34 @@
 #
 #
 
+#####################################
+# ::: Для проврки по нажатию кнопки 'отмены' в 'GitHub Action' :::
+
+# name: Thirteenth Workflow
+# on: push
+
+# jobs:
+#   # failure() success() always() cancelled()
+#   job:
+#     runs-on: ubuntu-latest
+#     steps:
+#       - name: First Step
+#         run: sleep 30                 # чтобы успеть нажать кнопку в 'GitHub Action'.
+#       - name: Runs on Canceled
+#         if: ${{ cancelled() }}        # вернёт 'true' если предидущие шаги были отменены.
+#         run: echo "Runs on Canceled"
+#       - name: Runs on any case
+#         if: ${{ always() }}           # возвращает 'true' при любом состоянии.
+#         run: echo "Runs on any case"
+#       - name: Runs on Success
+#         if: ${{ success() }}          # шаг удачный.
+#         run: echo "Runs on Success"
+#       - name: Runs on Failure
+#         if: ${{ failure() }}  # шаг не удачный.
+#         run: echo "Runs on Failure"
+
+################################
+#
 name: Thirteenth Workflow
 on: push
 
@@ -10,8 +38,9 @@ jobs:
   job:
     runs-on: ubuntu-latest
     steps:
-      - name: First Step
-        run: sleep 30                 # чтобы успеть нажать кнопку в 'GitHub Action'.
+      - name: Failure Step
+        id: error-step
+        run: exit 1
       - name: Runs on Canceled
         if: ${{ cancelled() }}        # вернёт 'true' если предидущие шаги были отменены.
         run: echo "Runs on Canceled"
@@ -22,5 +51,11 @@ jobs:
         if: ${{ success() }}          # шаг удачный.
         run: echo "Runs on Success"
       - name: Runs on Failure
-        if: ${{ failure() }}  # шаг не удачный.
+        if: ${{ failure() && steps.error-step.conclusion == 'failure' }}  # шаг не удачный.
         run: echo "Runs on Failure"
+  second-job:
+    runs-on: ubuntu-latest
+    needs: job
+    if: ${{ failure() }}
+    steps:
+      - run: echo "Job was failed"
